FORMAT: 1A
HOST: http://127.0.0.1:8000/

# Eko Putra Wijaya

Aplikasi ini merupaka sebuah game yang dapat dimainkan bersama teman melalui jaringan komputer. game yang dimaksud adalah game tic tac toe yang mana pada 1 game akan melibatkan 2 orang pemain.

# Cara menyalakan
Aplikasi ini dibangun menggunakan django. Untuk menyalakan server, buka cmd pada folder uas dan jalankan python manage.py runserver [ip]:[port].

# Mengakses Web Api
Api yang terdaftar terdapat pada path /api seperti /api/room/get
terdapat beberapa buah api yang dapat digunakan untuk memainkan game ini.

## API Collection [/api]

### Get or Create Room [GET /api/room/get]

+ Response 200 (application/json)

        [
            {
                "roomId": 11
            }
        ]

### Get Room Stats [GET /api/room/11]

+ Response 200 (application/json)
    
        [
            {
              "turn": 1,
              "c1": 0,
              "c2": 0,
              "c3": 0,
              "c4": 0,
              "c5": 0,
              "c6": 0,
              "c7": 0,
              "c8": 0,
              "c9": 0
            }
        ]

### GET Room Score [GET /api/room/11/score]

+ Response 200 (application/json)

        [
            {
                "p1": 0,
                "p2": 0
            }
        ]

### Get Opponent [GET /api/room/11/opponent]

+ Response 200 (application/json)

        [
            {
                "a": "admin",
                "b": "bawangsambal"
            }
        ]

### Game Ending [POST /api/room/11/end]

+ Response 200 (application/json)

### Record Move [POST /api/room/11/update]

+ Response 200 (application/json)