FORMAT: 1A
HOST: https://127.0.0.1:8000/

# Eko Putra Wijaya

Aplikasi ini merupaka sebuah game yang dapat dimainkan bersama teman melalui jaringan komputer. game yang dimaksud adalah game tic tac toe yang mana pada 1 game akan melibatkan 2 orang pemain.

# Cara menyalakan
Aplikasi ini dibangun menggunakan django. Untuk menyalakan server, buka cmd pada folder uas dan jalankan python manage.py runserver [ip]:[port].

# Mengakses Web Api
Api yang terdaftar terdapat pada path /api seperti /api/room/get
terdapat beberapa buah api yang dapat digunakan untuk memainkan game ini.

## API Collection [/api]

### Get or Create Room [GET /room/get]

+ Response 200 (application/json)

        [
            {
                "roomId": 11
            }
        ]