# Generated by Django 3.1 on 2021-05-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='c1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='c9',
            field=models.IntegerField(default=0),
        ),
    ]
